language: c
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service postgresql stop; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=ocsigen-start
  - OCAML_VERSION=4.03 PACKAGE=ocsigen-start
  - OCAML_VERSION=4.04 PACKAGE=ocsigen-start
os:
  - linux
  - osx
