language: c
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo service postgresql stop; fi
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02 PINS="eliom:https://github.com/ocsigen/eliom.git" PACKAGE=ocsigen-start POST_INSTALL_HOOK="cd ; eliom-distillery -y -name test -template os.pgocaml ; cd test ; make db-init ; make db-create ; make db-schema ; make test.byte"
  - OCAML_VERSION=4.03 PINS="eliom:https://github.com/ocsigen/eliom.git" PACKAGE=ocsigen-start POST_INSTALL_HOOK="cd ; eliom-distillery -y -name test -template os.pgocaml ; cd test ; make db-init ; make db-create ; make db-schema ; make test.byte"
  - OCAML_VERSION=4.04 PINS="eliom:https://github.com/ocsigen/eliom.git" PACKAGE=ocsigen-start POST_INSTALL_HOOK="cd ; eliom-distillery -y -name test -template os.pgocaml ; cd test ; make db-init ; make db-create ; make db-schema ; make test.byte"
os:
  - linux
  - osx
